-- ─── ReconAI initial schema ────────────────────────────────────────────────────
--
-- Run via:  supabase db push
--         or paste into Supabase Dashboard → SQL editor
--
-- The backend uses the service-role key and bypasses RLS entirely.
-- Tables are locked down so the anon key (used by the frontend) has zero access.

-- ─── Storage bucket ─────────────────────────────────────────────────────────────

-- Create the private bucket if it doesn't exist yet.
-- Alternatively: Supabase Dashboard → Storage → New bucket → "financial-documents", Private.
INSERT INTO storage.buckets (id, name, public)
VALUES ('financial-documents', 'financial-documents', false)
ON CONFLICT (id) DO NOTHING;

-- ─── Documents table ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS documents (
  -- doc_xxxxxxxx generated by generateDocumentId()
  id                TEXT        PRIMARY KEY,

  -- multer-generated on-disk filename; used as the lookup key from the API
  stored_name       TEXT        NOT NULL UNIQUE,
  original_name     TEXT        NOT NULL,
  size              INTEGER     NOT NULL,

  -- Tesseract output; null for non-image files
  ocr_text          TEXT,

  -- Keyword classification result
  category          TEXT        NOT NULL DEFAULT 'uncategorized',
  confidence        REAL        NOT NULL DEFAULT 0,
  matched_keywords  JSONB,

  -- Normalized fields extracted from OCR (merchant, amount, currency, date, ref#)
  structured_data   JSONB,

  -- Supabase Storage path: {documentId}/{storedName}; null if upload failed
  storage_path      TEXT,

  saved_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Transactions table ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS transactions (
  -- txn_xxxxxxxx generated by generateTransactionId()
  id                    TEXT        PRIMARY KEY,
  document_id           TEXT        NOT NULL REFERENCES documents(id) ON DELETE CASCADE,

  -- Carried from the parent document for self-contained ledger rows
  source_file           TEXT        NOT NULL,
  original_name         TEXT        NOT NULL,
  category              TEXT        NOT NULL,

  -- Extracted financial fields
  merchant              TEXT,
  amount                REAL,
  currency              TEXT,
  transaction_date      TEXT,           -- ISO date string YYYY-MM-DD
  reference_number      TEXT,

  -- Classification confidence (inherited from the document)
  confidence_score      REAL        NOT NULL DEFAULT 0,

  -- Within-document duplicate tracking (set by extractSoaTransactions)
  duplicate_group_id    TEXT,
  duplicate_flag        BOOLEAN     NOT NULL DEFAULT FALSE,

  -- OCR amount validation audit trail
  raw_ocr_text          TEXT,
  original_ocr_amount   REAL,
  amount_confidence     REAL,

  -- Stable key used for cross-document duplicate counting:
  -- "{category}|{merchant_normalized}|{amount_2dp}|{transaction_date}"
  normalized_key        TEXT,

  saved_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Indexes ────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_documents_saved_at
  ON documents(saved_at DESC);

CREATE INDEX IF NOT EXISTS idx_transactions_document_id
  ON transactions(document_id);

-- Used for O(n) duplicate counting via GROUP BY in db/index.js
CREATE INDEX IF NOT EXISTS idx_transactions_normalized_key
  ON transactions(normalized_key);

-- ─── Row-Level Security ─────────────────────────────────────────────────────────
--
-- Backend uses the service-role key → bypasses RLS (full access, no policies needed).
-- Frontend uses the anon key → hits RLS → blocked by default (no public policies).
-- This prevents any direct frontend → database access.

ALTER TABLE documents    ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- Storage bucket policy: service role has implicit full access.
-- No public policies = no anonymous access.
